[2024-04-03T04:02:44.751+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_into_table permission to 509
[2024-04-03T04:02:44.752+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T04:02:44.753+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2 permission to 509
[2024-04-03T04:02:44.754+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T04:02:44.791+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_into_table permission to 509
[2024-04-03T04:02:44.794+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T04:02:44.796+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2 permission to 509
[2024-04-03T04:02:44.798+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T04:02:44.837+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_postgres_operator_v2.insert_into_table scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T04:02:44.851+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_postgres_operator_v2.insert_into_table scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T04:02:44.852+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-03T04:02:44.869+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-04-02 00:00:00+00:00
[2024-04-03T04:02:44.873+0000] {standard_task_runner.py:60} INFO - Started process 8386 to run task
[2024-04-03T04:02:44.875+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_postgres_operator_v2', 'insert_into_table', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp8t8uaph_']
[2024-04-03T04:02:44.878+0000] {standard_task_runner.py:88} INFO - Job 247: Subtask insert_into_table
[2024-04-03T04:02:44.923+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_into_table permission to 509
[2024-04-03T04:02:44.926+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T04:02:44.929+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator_v2 permission to 509
[2024-04-03T04:02:44.931+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T04:02:44.933+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_postgres_operator_v2.insert_into_table scheduled__2024-04-02T00:00:00+00:00 [running]> on host 46dc445f2ec8
[2024-04-03T04:02:44.975+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'insert_into_table', field 'sql'. Template: "insert into dag_runs values ( '{{ dt }}', '{{ dag.dag_id }}')"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dt' is undefined
[2024-04-03T04:02:44.979+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2360, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2498, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2910, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dt' is undefined
[2024-04-03T04:02:44.988+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_postgres_operator_v2, task_id=insert_into_table, execution_date=20240402T000000, start_date=20240403T040244, end_date=20240403T040244
[2024-04-03T04:02:45.001+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 247 for task insert_into_table ('dt' is undefined; 8386)
[2024-04-03T04:02:45.008+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T04:02:45.025+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
