[2024-04-03T03:43:21.861+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=create_postgres_table permission to 509
[2024-04-03T03:43:21.863+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T03:43:21.865+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator permission to 509
[2024-04-03T03:43:21.866+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T03:43:21.896+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=create_postgres_table permission to 509
[2024-04-03T03:43:21.899+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T03:43:21.901+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator permission to 509
[2024-04-03T03:43:21.903+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T03:43:21.983+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_postgres_operator.create_postgres_table scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T03:43:21.993+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_postgres_operator.create_postgres_table scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T03:43:21.994+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-03T03:43:22.019+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-04-02 00:00:00+00:00
[2024-04-03T03:43:22.023+0000] {standard_task_runner.py:60} INFO - Started process 7001 to run task
[2024-04-03T03:43:22.026+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_postgres_operator', 'create_postgres_table', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpgcbd1k51']
[2024-04-03T03:43:22.029+0000] {standard_task_runner.py:88} INFO - Job 244: Subtask create_postgres_table
[2024-04-03T03:43:22.075+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=create_postgres_table permission to 509
[2024-04-03T03:43:22.077+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T03:43:22.078+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=dag_postgres_operator permission to 509
[2024-04-03T03:43:22.079+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T03:43:22.082+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_postgres_operator.create_postgres_table scheduled__2024-04-02T00:00:00+00:00 [running]> on host 46dc445f2ec8
[2024-04-03T03:43:22.179+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_postgres_operator' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-04-03T03:43:22.181+0000] {sql.py:276} INFO - Executing: create table if not exists dag_runs (
        dt date,
        dag_id character varying,
        primary key (dt, dag_id)
        )
[2024-04-03T03:43:22.193+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T03:43:22.214+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T03:43:22.333+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Name or service not known

[2024-04-03T03:43:22.355+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_postgres_operator, task_id=create_postgres_table, execution_date=20240402T000000, start_date=20240403T034321, end_date=20240403T034322
[2024-04-03T03:43:22.371+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 244 for task create_postgres_table (could not translate host name "host.docker.local" to address: Name or service not known
; 7001)
[2024-04-03T03:43:22.411+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T03:43:22.429+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
