[2024-04-03T23:54:07.457+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_data permission to 509
[2024-04-03T23:54:07.458+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T23:54:07.459+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag permission to 509
[2024-04-03T23:54:07.460+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T23:54:07.485+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_data permission to 509
[2024-04-03T23:54:07.487+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T23:54:07.489+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag permission to 509
[2024-04-03T23:54:07.491+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T23:54:07.531+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_practice_dag.insert_data scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T23:54:07.543+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_practice_dag.insert_data scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T23:54:07.544+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 8
[2024-04-03T23:54:07.559+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-04-02 00:00:00+00:00
[2024-04-03T23:54:07.563+0000] {standard_task_runner.py:60} INFO - Started process 732 to run task
[2024-04-03T23:54:07.566+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'second_practice_dag', 'insert_data', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/second_practice_dag.py', '--cfg-path', '/tmp/tmpww06m4fd']
[2024-04-03T23:54:07.569+0000] {standard_task_runner.py:88} INFO - Job 277: Subtask insert_data
[2024-04-03T23:54:07.617+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_data permission to 509
[2024-04-03T23:54:07.619+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T23:54:07.620+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag permission to 509
[2024-04-03T23:54:07.622+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T23:54:07.624+0000] {task_command.py:423} INFO - Running <TaskInstance: second_practice_dag.insert_data scheduled__2024-04-02T00:00:00+00:00 [running]> on host 235f0c517704
[2024-04-03T23:54:07.704+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jacob Monks' AIRFLOW_CTX_DAG_ID='second_practice_dag' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-04-03T23:54:07.706+0000] {sql.py:276} INFO - Executing: 
            insert into practice_table values ('2024-04-02', 'second_practice_dag', 'Jacob Monks');
[2024-04-03T23:54:07.717+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T23:54:07.731+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T23:54:07.744+0000] {sql.py:457} INFO - Running statement: 
            insert into practice_table values ('2024-04-02', 'second_practice_dag', 'Jacob Monks');, parameters: None
[2024-04-03T23:54:07.751+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "practice_table_pkey"
DETAIL:  Key (dt, dag_run)=(2024-04-02, second_practice_dag) already exists.

[2024-04-03T23:54:07.758+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=second_practice_dag, task_id=insert_data, execution_date=20240402T000000, start_date=20240403T235407, end_date=20240403T235407
[2024-04-03T23:54:07.769+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 277 for task insert_data (duplicate key value violates unique constraint "practice_table_pkey"
DETAIL:  Key (dt, dag_run)=(2024-04-02, second_practice_dag) already exists.
; 732)
[2024-04-03T23:54:07.779+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T23:54:07.794+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-03T23:54:07.806+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
