[2024-04-03T23:53:28.032+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_data permission to 509
[2024-04-03T23:53:28.035+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T23:53:28.037+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag permission to 509
[2024-04-03T23:53:28.038+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T23:53:28.062+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_data permission to 509
[2024-04-03T23:53:28.065+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T23:53:28.067+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag permission to 509
[2024-04-03T23:53:28.068+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T23:53:28.107+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_practice_dag.insert_data scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T23:53:28.117+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_practice_dag.insert_data scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-04-03T23:53:28.118+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 7
[2024-04-03T23:53:28.131+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-04-02 00:00:00+00:00
[2024-04-03T23:53:28.135+0000] {standard_task_runner.py:60} INFO - Started process 648 to run task
[2024-04-03T23:53:28.137+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'second_practice_dag', 'insert_data', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/second_practice_dag.py', '--cfg-path', '/tmp/tmp5mwvgm6a']
[2024-04-03T23:53:28.139+0000] {standard_task_runner.py:88} INFO - Job 274: Subtask insert_data
[2024-04-03T23:53:28.186+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00/task_id=insert_data permission to 509
[2024-04-03T23:53:28.190+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag/run_id=scheduled__2024-04-02T00:00:00+00:00 permission to 509
[2024-04-03T23:53:28.192+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=second_practice_dag permission to 509
[2024-04-03T23:53:28.195+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-04-03T23:53:28.199+0000] {task_command.py:423} INFO - Running <TaskInstance: second_practice_dag.insert_data scheduled__2024-04-02T00:00:00+00:00 [running]> on host 235f0c517704
[2024-04-03T23:53:28.281+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jacob Monks' AIRFLOW_CTX_DAG_ID='second_practice_dag' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-04-03T23:53:28.282+0000] {sql.py:276} INFO - Executing: 
            insert into practice_table values ('2024-04-02', 'second_practice_dag', 'Jacob Monks');
[2024-04-03T23:53:28.290+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T23:53:28.301+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T23:53:28.312+0000] {sql.py:457} INFO - Running statement: 
            insert into practice_table values ('2024-04-02', 'second_practice_dag', 'Jacob Monks');, parameters: None
[2024-04-03T23:53:28.316+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "practice_table_pkey"
DETAIL:  Key (dt, dag_run)=(2024-04-02, second_practice_dag) already exists.

[2024-04-03T23:53:28.324+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=second_practice_dag, task_id=insert_data, execution_date=20240402T000000, start_date=20240403T235328, end_date=20240403T235328
[2024-04-03T23:53:28.340+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 274 for task insert_data (duplicate key value violates unique constraint "practice_table_pkey"
DETAIL:  Key (dt, dag_run)=(2024-04-02, second_practice_dag) already exists.
; 648)
[2024-04-03T23:53:28.350+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T23:53:28.369+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-03T23:53:28.384+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
